export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'

export const ADD_POST = 'ADD_POST'
export const ADD_COMMENT = 'ADD_COMMENT'

export const UPDATE_POST = 'UPDATE_POST'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'

export const REMOVE_COMMENT = 'REMOVE_COMMENT'
export const REMOVE_POST = 'REMOVE_POST'

export const SortBy = {
  VOTESCORE: 'VOTESCORE',
  TIMESTAMP: 'TIMESTAMP'
}
